#pragma once
#define PLAYER_OVERALL_SCALE 3

#define ENEMY_SPAWN_DELAY 250
#define SPAWN_ACCELERATION 5
#define MIN_SPAWN_DELAY 100

#define FIRE_DELAY 2
#define BULLET_SPEED 6
#define BULLET_DAMAGE 1
#define BULLET_SCALE .0075f * PLAYER_OVERALL_SCALE
#define GUN_SCALE .05f * PLAYER_OVERALL_SCALE


#define ENEMY_SPEED .1
#define ENEMY_DAMAGE 1
#define ENEMY_HEALTH 1
#define ENEMY_SCALE .07f


#define PLAYER_SPEED .6
#define PLAYER_HEALTH 5
#define PLAYER_SCALE .05f * PLAYER_OVERALL_SCALE