#pragma once
#define PLAYER_OVERALL_SCALE 2

#define ENEMY_SPAWN_DELAY 5000
#define SPAWN_ACCELERATION 250
#define MIN_SPAWN_DELAY 2000

#define FIRE_DELAY 500
#define BULLET_SPEED 10
#define BULLET_DAMAGE 1
#define BULLET_SCALE .05f * PLAYER_OVERALL_SCALE
#define GUN_SCALE .05f * PLAYER_OVERALL_SCALE


#define ENEMY_SPEED .25
#define ENEMY_DAMAGE 1
#define ENEMY_HEALTH 1
#define ENEMY_SCALE .05f


#define PLAYER_SPEED .6
#define PLAYER_HEALTH 1
#define PLAYER_SCALE .05f * PLAYER_OVERALL_SCALE